-- ================================================================
-- Database: bjmetro
-- Type: mock data
-- Description: Metro mock data is generated by backend APIs.
-- Execute after bjmetro_schema.sql if you need a placeholder file.
-- ================================================================

USE bjmetro;
-- No standalone mock insert SQL is required.
-- In the UI, open BJ Metro module and click initialization/seed buttons.
