-- ================================================================
-- Database: regdb
-- Type: mock data
-- Description: Regulatory mock data is generated by backend APIs.
-- Execute after regdb_schema.sql if you need a placeholder file.
-- ================================================================

USE regdb;
-- No standalone mock insert SQL is required.
-- In the UI, open Regulatory module and click initialization/seed buttons.
